import 'call_repo_providers.dart';
import 'dart:async';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/index.dart';
import '../../data/models/ice_candidate_model.dart';
import '../../../../core/providers/index.dart';
import '../../../auth/presentation/providers/index.dart';
import 'call_uc_providers.dart';
import '../../domain/repositories/call_repository.dart';
import '../../domain/usecases/index.dart';
// RE-EXPORT
export 'call_repo_providers.dart';
export 'call_uc_providers.dart';

/// State of the active call, including streams and connection status.
class CallState {
  final CallEntity? call;
  final RTCVideoRenderer localRenderer;
  final RTCVideoRenderer remoteRenderer;
  final bool isMicOn;
  final bool isCameraOn;

  CallState({
    this.call,
    required this.localRenderer,
    required this.remoteRenderer,
    this.isMicOn = true,
    this.isCameraOn = true,
  });

  CallState copyWith({CallEntity? call, bool? isMicOn, bool? isCameraOn}) {
    return CallState(
      call: call ?? this.call,
      localRenderer: localRenderer,
      remoteRenderer: remoteRenderer,
      isMicOn: isMicOn ?? this.isMicOn,
      isCameraOn: isCameraOn ?? this.isCameraOn,
    );
  }
}

final incomingCallStreamProvider = StreamProvider.autoDispose<CallEntity?>((
  ref,
) {
  final watchIncomingCallsUseCase = ref.watch(
    watchIncomingCallsUseCaseProvider,
  );
  final userId = ref.watch(userIdProvider);
  if (userId == null) return const Stream.empty();
  return watchIncomingCallsUseCase.call(userId);
});

// Note: callRepositoryProvider is now exported from call_repo_providers.dart

final callProvider = StateNotifierProvider<CallNotifier, CallState>((ref) {
  return CallNotifier(
    startCallUseCase: ref.watch(startCallUseCaseProvider),
    acceptCallUseCase: ref.watch(acceptCallUseCaseProvider),
    endCallUseCase: ref.watch(endCallUseCaseProvider),
    rejectCallUseCase: ref.watch(rejectCallUseCaseProvider),
    watchCallUseCase: ref.watch(watchCallUseCaseProvider),
    repository: ref.watch(
      callRepositoryProvider,
    ), // Still needed for ICE candidates for now until fully refactored
  );
});

class CallNotifier extends StateNotifier<CallState> {
  final StartCallUseCase _startCallUseCase;
  final AcceptCallUseCase _acceptCallUseCase;
  final EndCallUseCase _endCallUseCase;
  final RejectCallUseCase _rejectCallUseCase;
  final WatchCallUseCase _watchCallUseCase;

  // TODO: Refactor ICE candidates logic to UseCases
  final CallRepository _repository;

  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;
  StreamSubscription? _callSubscription;
  StreamSubscription? _iceSubscription;

  CallNotifier({
    required StartCallUseCase startCallUseCase,
    required AcceptCallUseCase acceptCallUseCase,
    required EndCallUseCase endCallUseCase,
    required RejectCallUseCase rejectCallUseCase,
    required WatchCallUseCase watchCallUseCase,
    required CallRepository repository,
  }) : _startCallUseCase = startCallUseCase,
       _acceptCallUseCase = acceptCallUseCase,
       _endCallUseCase = endCallUseCase,
       _rejectCallUseCase = rejectCallUseCase,
       _watchCallUseCase = watchCallUseCase,
       _repository = repository,
       super(
         CallState(
           localRenderer: RTCVideoRenderer(),
           remoteRenderer: RTCVideoRenderer(),
         ),
       ) {
    _initRenderers();
  }

  Future<void> _initRenderers() async {
    await state.localRenderer.initialize();
    await state.remoteRenderer.initialize();
  }

  /// Start a new call.
  Future<void> startCall({
    required String callerUid,
    required String calleeUid,
    CallType type = CallType.video,
  }) async {
    final call = CallEntity(
      id: '', // Will be generated by Firestore
      callerUid: callerUid,
      calleeUid: calleeUid,
      status: CallStatus.ringing,
      type: type,
      createdAt: DateTime.now(),
    );

    await _setupPeerConnection(call, true);

    // Create offer
    final offer = await _peerConnection!.createOffer({
      'offerToReceiveVideo': type == CallType.video ? 1 : 0,
      'offerToReceiveAudio': 1,
    });
    await _peerConnection!.setLocalDescription(offer);

    final result = await _startCallUseCase.call(
      call.copyWith(offer: offer.toMap()),
    );

    result.fold(
      (failure) {
        // Handle failure (e.g. show toast, or update state with error)
      },
      (callId) {
        state = state.copyWith(
          call: call.copyWith(id: callId, offer: offer.toMap()),
        );
        _listenToCallUpdates(callId);
        _listenToIceCandidates(callId, false);
      },
    );
  }

  Future<void> acceptCall(CallEntity call) async {
    state = state.copyWith(call: call);
    await _setupPeerConnection(call, false);
    await _peerConnection!.setRemoteDescription(
      RTCSessionDescription(call.offer!['sdp'], call.offer!['type']),
    );

    final answer = await _peerConnection!.createAnswer();
    await _peerConnection!.setLocalDescription(answer);

    final result = await _acceptCallUseCase.call(
      AcceptCallParams(callId: call.id, answer: answer.toMap()),
    );

    result.fold(
      (failure) {
        // Handle failure
      },
      (_) {
        _listenToCallUpdates(call.id);
        _listenToIceCandidates(
          call.id,
          true,
        ); // Listen for candidates from caller
      },
    );
  }

  Future<void> _setupPeerConnection(CallEntity call, bool isCaller) async {
    final configuration = {
      'iceServers': [
        {'urls': 'stun:stun.l.google.com:19302'},
        {'urls': 'stun:stun1.l.google.com:19302'},
      ],
    };

    _peerConnection = await createPeerConnection(configuration);

    // Get local stream
    final constraints = {
      'audio': true,
      'video': call.type == CallType.video ? {'facingMode': 'user'} : false,
    };
    _localStream = await navigator.mediaDevices.getUserMedia(constraints);
    state.localRenderer.srcObject = _localStream;

    // Add local stream tracks to peer connection
    _localStream!.getTracks().forEach((track) {
      _peerConnection!.addTrack(track, _localStream!);
    });

    // Handle remote stream
    _peerConnection!.onTrack = (event) {
      if (event.streams.isNotEmpty) {
        state.remoteRenderer.srcObject = event.streams[0];
      }
    };

    // Handle ICE candidates
    _peerConnection!.onIceCandidate = (candidate) {
      if (candidate.candidate != null) {
        _repository.addIceCandidate(
          call.id,
          IceCandidateModel(
            candidate: candidate.candidate!,
            sdpMid: candidate.sdpMid!,
            sdpMLineIndex: candidate.sdpMLineIndex!,
          ),
          isCaller,
        );
      }
    };
  }

  void _listenToCallUpdates(String callId) {
    _callSubscription?.cancel();
    _callSubscription = _watchCallUseCase.call(callId).listen((call) {
      if (call == null) return;

      if (call.status == CallStatus.ended ||
          call.status == CallStatus.rejected) {
        hangUp();
      } else if (call.status == CallStatus.accepted &&
          call.answer != null &&
          _peerConnection != null) {
        _peerConnection!.setRemoteDescription(
          RTCSessionDescription(call.answer!['sdp'], call.answer!['type']),
        );
      }

      state = state.copyWith(call: call);
    });
  }

  void _listenToIceCandidates(String callId, bool fromCaller) {
    _iceSubscription?.cancel();
    _iceSubscription = _repository
        .watchIceCandidates(callId, fromCaller)
        .listen((candidates) {
          for (final candidate in candidates) {
            _peerConnection?.addCandidate(
              RTCIceCandidate(
                candidate.candidate,
                candidate.sdpMid,
                candidate.sdpMLineIndex,
              ),
            );
          }
        });
  }

  Future<void> hangUp() async {
    if (state.call != null) {
      await _endCallUseCase.call(state.call!.id);
    }

    await _callSubscription?.cancel();
    await _iceSubscription?.cancel();
    await _localStream?.dispose();
    await _peerConnection?.dispose();
    state.localRenderer.srcObject = null;
    state.remoteRenderer.srcObject = null;
    if (mounted) {
      state = state.copyWith(call: null);
    }
  }

  Future<void> rejectCall(String callId) async {
    await _rejectCallUseCase.call(callId);
    if (mounted) state = state.copyWith(call: null);
  }

  void toggleMic() {
    if (_localStream != null) {
      final enabled = !state.isMicOn;
      _localStream!.getAudioTracks().forEach(
        (track) => track.enabled = enabled,
      );
      if (mounted) state = state.copyWith(isMicOn: enabled);
    }
  }

  void toggleCamera() {
    if (_localStream != null) {
      final enabled = !state.isCameraOn;
      _localStream!.getVideoTracks().forEach(
        (track) => track.enabled = enabled,
      );
      if (mounted) state = state.copyWith(isCameraOn: enabled);
    }
  }

  @override
  void dispose() {
    // Fire-and-forget hangUp: we can't await in dispose()
    // Guard with mounted checks inside hangUp() to prevent state updates
    hangUp().catchError((_) {});
    state.localRenderer.dispose();
    state.remoteRenderer.dispose();
    super.dispose();
  }
}
