/// Provider for managing the Video/Audio call state and WebRTC logic.
library;

import 'dart:async';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/index.dart';
import '../../domain/repositories/call_repository.dart';
import '../../data/repositories/firebase_call_repository.dart';
import '../../data/models/ice_candidate_model.dart';
import '../../../../core/providers/index.dart';
import '../../../../core/providers/auth_provider.dart';

/// State of the active call, including streams and connection status.
class CallState {
  final CallEntity? call;
  final RTCVideoRenderer localRenderer;
  final RTCVideoRenderer remoteRenderer;
  final bool isMicOn;
  final bool isCameraOn;

  CallState({
    this.call,
    required this.localRenderer,
    required this.remoteRenderer,
    this.isMicOn = true,
    this.isCameraOn = true,
  });

  CallState copyWith({
    CallEntity? call,
    bool? isMicOn,
    bool? isCameraOn,
  }) {
    return CallState(
      call: call ?? this.call,
      localRenderer: localRenderer,
      remoteRenderer: remoteRenderer,
      isMicOn: isMicOn ?? this.isMicOn,
      isCameraOn: isCameraOn ?? this.isCameraOn,
    );
  }
}

final incomingCallStreamProvider = StreamProvider.autoDispose<CallEntity?>((ref) {
  final repository = ref.watch(callRepositoryProvider);
  final userId = ref.watch(currentUserIdProvider);
  if (userId == null) return const Stream.empty();
  return repository.watchIncomingCalls(userId);
});

final callRepositoryProvider = Provider<CallRepository>((ref) {
  return FirebaseCallRepository();
});

final callProvider = StateNotifierProvider<CallNotifier, CallState>((ref) {
  final repository = ref.watch(callRepositoryProvider);
  return CallNotifier(repository);
});

class CallNotifier extends StateNotifier<CallState> {
  final CallRepository _repository;
  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;
  StreamSubscription? _callSubscription;
  StreamSubscription? _iceSubscription;

  CallNotifier(this._repository)
      : super(CallState(
          localRenderer: RTCVideoRenderer(),
          remoteRenderer: RTCVideoRenderer(),
        )) {
    _initRenderers();
  }

  Future<void> _initRenderers() async {
    await state.localRenderer.initialize();
    await state.remoteRenderer.initialize();
  }

  /// Start a new call.
  Future<void> startCall({required String callerUid, required String calleeUid, CallType type = CallType.video}) async {
    final call = CallEntity(
      id: '', // Will be generated by Firestore
      callerUid: callerUid,
      calleeUid: calleeUid,
      status: CallStatus.ringing,
      type: type,
      createdAt: DateTime.now(),
    );

    await _setupPeerConnection(call, true);
    
    // Create offer
    final offer = await _peerConnection!.createOffer({
      'offerToReceiveVideo': type == CallType.video ? 1 : 0,
      'offerToReceiveAudio': 1,
    });
    await _peerConnection!.setLocalDescription(offer);

    final callId = await _repository.startCall(call.copyWith(offer: offer.toMap()));
    state = state.copyWith(call: call.copyWith(id: callId, offer: offer.toMap()));

    _listenToCallUpdates(callId);
    _listenToIceCandidates(callId, false); // Listen for candidates from callee
  }

  /// Accept an incoming call.
  Future<void> acceptCall(CallEntity call) async {
    state = state.copyWith(call: call);
    await _setupPeerConnection(call, false);

    // Set remote description from offer
    await _peerConnection!.setRemoteDescription(
      RTCSessionDescription(call.offer!['sdp'], call.offer!['type']),
    );

    // Create answer
    final answer = await _peerConnection!.createAnswer();
    await _peerConnection!.setLocalDescription(answer);

    await _repository.acceptCall(call.id, answer.toMap());
    
    _listenToCallUpdates(call.id);
    _listenToIceCandidates(call.id, true); // Listen for candidates from caller
  }

  Future<void> _setupPeerConnection(CallEntity call, bool isCaller) async {
    final configuration = {
      'iceServers': [
        {'urls': 'stun:stun.l.google.com:19302'},
        {'urls': 'stun:stun1.l.google.com:19302'},
      ]
    };

    _peerConnection = await createPeerConnection(configuration);

    // Get local stream
    final constraints = {
      'audio': true,
      'video': call.type == CallType.video ? {'facingMode': 'user'} : false,
    };
    _localStream = await navigator.mediaDevices.getUserMedia(constraints);
    state.localRenderer.srcObject = _localStream;

    // Add local stream tracks to peer connection
    _localStream!.getTracks().forEach((track) {
      _peerConnection!.addTrack(track, _localStream!);
    });

    // Handle remote stream
    _peerConnection!.onTrack = (event) {
      if (event.streams.isNotEmpty) {
        state.remoteRenderer.srcObject = event.streams[0];
      }
    };

    // Handle ICE candidates
    _peerConnection!.onIceCandidate = (candidate) {
      if (candidate.candidate != null) {
        _repository.addIceCandidate(
          call.id,
          IceCandidateModel(
            candidate: candidate.candidate!,
            sdpMid: candidate.sdpMid!,
            sdpMLineIndex: candidate.sdpMLineIndex!,
          ),
          isCaller,
        );
      }
    };
  }

  void _listenToCallUpdates(String callId) {
    _callSubscription?.cancel();
    _callSubscription = _repository.watchCall(callId).listen((call) {
      if (call == null) return;
      
      if (call.status == CallStatus.ended || call.status == CallStatus.rejected) {
        hangUp();
      } else if (call.status == CallStatus.accepted && call.answer != null && _peerConnection != null) {
        _peerConnection!.setRemoteDescription(
          RTCSessionDescription(call.answer!['sdp'], call.answer!['type']),
        );
      }
      
      state = state.copyWith(call: call);
    });
  }

  void _listenToIceCandidates(String callId, bool fromCaller) {
    _iceSubscription?.cancel();
    _iceSubscription = _repository.watchIceCandidates(callId, fromCaller).listen((candidates) {
      for (final candidate in candidates) {
        _peerConnection?.addCandidate(
          RTCIceCandidate(candidate.candidate, candidate.sdpMid, candidate.sdpMLineIndex),
        );
      }
    });
  }

  Future<void> hangUp() async {
    if (state.call != null) {
      await _repository.endCall(state.call!.id);
    }
    
    await _callSubscription?.cancel();
    await _iceSubscription?.cancel();
    await _localStream?.dispose();
    await _peerConnection?.dispose();
    state.localRenderer.srcObject = null;
    state.remoteRenderer.srcObject = null;
    state = state.copyWith(call: null);
  }

  Future<void> rejectCall(String callId) async {
    await _repository.rejectCall(callId);
    state = state.copyWith(call: null);
  }

  void toggleMic() {
    if (_localStream != null) {
      final enabled = !state.isMicOn;
      _localStream!.getAudioTracks().forEach((track) => track.enabled = enabled);
      state = state.copyWith(isMicOn: enabled);
    }
  }

  void toggleCamera() {
    if (_localStream != null) {
      final enabled = !state.isCameraOn;
      _localStream!.getVideoTracks().forEach((track) => track.enabled = enabled);
      state = state.copyWith(isCameraOn: enabled);
    }
  }

  @override
  void dispose() {
    hangUp();
    state.localRenderer.dispose();
    state.remoteRenderer.dispose();
    super.dispose();
  }
}
